name: macos

on:
  push:
    branches:
      - master
    paths:
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**
  pull_request:
    paths:
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - uses: actions/checkout@v2

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
      
    - name: Add custom conan repo
      run: conan remote add owl https://api.bintray.com/conan/zethon/owl

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
      
    - name: Configure Conan
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: conan install $GITHUB_WORKSPACE -s build_type=$BUILD_TYPE --build missing

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_ASH_TESTS=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
