name: Windows

on:
  push:
    branches:
      - master
    paths:
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**     
  pull_request:
    paths:
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Add custom conan repo
      run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

    - name: Create Build Environment
      working-directory: ${{github.workspace}}
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure Conan
      working-directory: ${{github.workspace}}/build
      run: conan install ${{github.workspace}} -s build_type=$BUILD_TYPE --build missing

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION="10.0.18362.0" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_ASH_TESTS=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C $BUILD_TYPE
